#!/usr/bin/env python
# mypy: ignore-errors
#
#
# run speedo server
#
#

import os
import uvicorn

from speedo_server.alembic.update import run_alembic


if os.getenv("SPEEDO_ALEMBIC", "") != "":
    run_alembic()

if __name__ == "__main__":
    uvicorn.run(
        "speedo_server.asgi:app", host="0.0.0.0", port=8000
    )  # , log_level="info"
