name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: nix-shell -I nixpkgs=https://github.com/nokx5/nokxpkgs/archive/main.tar.gz -p black --run 'black --check .'
      - run: nix-build -I nokxpkgs=https://github.com/nokx5/nokxpkgs/archive/main.tar.gz -A python3Packages.speedo --no-out-link
      - run: nix-build -I nokxpkgs=https://github.com/nokx5/nokxpkgs/archive/main.tar.gz -A python3Packages.speedo_client --no-out-link
      
